config/routes.rb
Rails.application.routes.draw do

  #顧客用
  devise_for :customers, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers:{
    sessions: "admin/sessions"
  }

  #顧客用
  scope module: :public do
    root to: 'homes#top'
    get "home/about" => "homes#about", as: "about"
    get "customers/mypage" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/confirm" => "customers#confirm"
    patch "customers/withdrawal" => "customers#withdrawal"


    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :genres, only: [:show]
  end


  #管理者用
  namespace :admin do
    get '/' => 'orders#index'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]

  end

 # 退会確認画面
 get  '/customers/check' => 'customers#check'
 # 論理削除用のルーティング
 patch  '/customers/withdraw' => 'customers#withdraw'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postal_code, presence: true, numericality: true, length: { is: 7 }
  validates :address, presence: true
  validates :name, presence: true

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
    #小計を求める
    def subtotal
        item.with_tax_price * amount
    end
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true, numericality: true, length: { is: 7 }
  validates :phone_number, presence: true, numericality: true

  def full_name
    last_name + '' + first_name
  end

  #ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないようにする。
  # def active_for_authentication?
  #   super && (is_active == false)
  # end

end

app/models/genre.rb
class Genre < ApplicationRecord

   has_many :items, dependent: :destroy

   validates :name, presence: true, length: { minimum: 1 }

end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  belongs_to :genre

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  TAX_RATE = 10

  def with_tax_price
   (price * (1 + TAX_RATE * 0.01)).floor
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def total_item_amount #アイテム合計金額
   order_details.sum { |order_detail| order_detail.subtotal }
  end
  
  

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :postal_code, presence: true, numericality: true, length: { is: 7 }
  validates :address, presence: true
  validates :name, presence: true

  def full_name
    last_name + '' + first_name
  end

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum make_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

   def subtotal
    unit_price * amount
   end



end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page])
  end

  def about

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(12)
    @genres = Genre.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
    @cart_item_new = CartItem.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    orders = Order.order("created_at desc")
    @orders = Kaminari.paginate_array(orders).page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total_item_amount = @order_details.sum { |order_detail| order_detail.subtotal }
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
       @order_details.update_all(make_status: 1) if @order.status == "payment_confirmation"
    end
    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/orders/index.html.erb
<div class="container">

  <div class="row">
    <div class="m-4">
      <h3>注文履歴一覧</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-10 mx-auto">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td>
                  <%= link_to admin_order_path(order.id) do %>
                    <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                  <% end %>
                </td>
                <td><%= order.customer.last_name + order.customer.first_name %></td>
                <td><%= order.order_details.sum(:amount) %></td>
                <td><%= t("enums.order.order_status.#{order.status_i18n}") %></td>
              </tr>
            <% end %>
          </tbody>
        </thead>
      </table>
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">

  <div class="row">
    <div class="m-4">
      <h4>注文履歴詳細</h4>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6 mx-5 my-2">
      <!--購入者情報-->
      <table class="table table-borderless">
        <tr>
          <td>購入者</td>
          <td><%= @order.customer.full_name %></td>
        </tr>
        <tr>
          <td>注文日</td>
          <td><%= @order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
        </tr>
        <tr>
          <td>配送先</td>
          <td>
            <%= @order.address %><br>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <td>支払方法</td>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <td>注文ステータス</td>
          <td>
            <%= form_with model: @order, url: admin_order_path(@order), method: :patch do |f| %>
              <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
              <%= f.submit '更新', class: "btn btn-sm btn-outline-danger" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-8 my-3">
      <!--商品情報-->
      <table class="table table-hover table-inverse mx-auto">
        <thead class="table-danger">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.unit_price %></td>
              <td><%= order_detail.amount %></td>
              <td><%= order_detail.subtotal %></td>
                <td>
                  <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
                  <%= f.select :make_status, OrderDetail.make_statuses.keys.map {|k| [I18n.t("enums.order_detail.make_status.#{k}"), k]} %>
                  　<%= f.submit '更新',  class: "btn btn-sm btn-outline-danger" %>
                  <% end %>
                </td>
            </tr>
        　<% end %>
        </tbody>
      </table>
    </div>

    <div class="col-lg-3 mx-auto mt-5">
      <!--金額-->
      <table class="table table-borderless">
        <tr>
          <td>商品合計</td>
          <td><%= @total_item_amount.to_s(:delimited) %></td>
        </tr>
        <tr>
          <td>送料合計</td>
          <td><%= @order.postage.to_s(:delimited) %></td>
        </tr>
        <tr>
          <td>請求金額合計</td>
          <td><%=  @order.total_amount.to_s(:delimited) %></td>
        </tr>
      </table>
    </div>
  </div>
</div>