config/routes.rb
Rails.application.routes.draw do

  #顧客用
  devise_for :customers, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers:{
    sessions: "admin/sessions"
  }

  #顧客用
  scope module: :public do
    root to: 'homes#top'
    get "home/about" => "homes#about", as: "about"
    get "customers/mypage" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/confirm" => "customers#confirm"
    patch "customers/withdrawal" => "customers#withdrawal"


    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :genres, only: [:show]
  end


  #管理者用
  namespace :admin do
    get '/' => 'orders#index'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]

  end

 # 退会確認画面
 get  '/customers/check' => 'customers#check'
 # 論理削除用のルーティング
 patch  '/customers/withdraw' => 'customers#withdraw'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postal_code, presence: true, numericality: true, length: { is: 7 }
  validates :address, presence: true
  validates :name, presence: true

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
    #小計を求める
    def subtotal
        item.with_tax_price * amount
    end
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true, numericality: true, length: { is: 7 }
  validates :phone_number, presence: true, numericality: true

  def full_name
    last_name + '' + first_name
  end

  #ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないようにする。
  # def active_for_authentication?
  #   super && (is_active == false)
  # end

end

app/models/genre.rb
class Genre < ApplicationRecord

   has_many :items, dependent: :destroy

   validates :name, presence: true, length: { minimum: 1 }

end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  belongs_to :genre

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  TAX_RATE = 10

  def with_tax_price
   (price * (1 + TAX_RATE * 0.01)).floor
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def total_item_amount #アイテム合計金額
   order_details.sum { |order_detail| order_detail.subtotal }
  end
  
  

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :postal_code, presence: true, numericality: true, length: { is: 7 }
  validates :address, presence: true
  validates :name, presence: true

  def full_name
    last_name + '' + first_name
  end

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum make_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

   def subtotal
    unit_price * amount
   end



end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page])
  end

  def about

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight nagano cake</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg">
      <div class="container p-3">
        <!--ロゴ-->
        <%= link_to root_path, class: 'brand-logo' do %>
          <%= image_tag 'logo.png', size:"50x50" %>
        <% end %>

        <!--customerログイン時、ようこそ○○さん！-->
        <% if customer_signed_in? %>
        <div class="log-in-message">ようこそ、<%= current_customer.last_name %>さん！</div>

        <% else %>

        <% end %>



        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"><i class="fa-solid fa-chevron-down"></i></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
            <!--customerログイン時-->
              <li>
                <%= link_to customers_mypage_path, class: 'nav-link text-dark' do %>
                 My page
                <% end %>
              </li>

              <li>
                <%= link_to items_path, class: 'nav-link text-dark' do %>
                  Items
                <% end %>
                </li>

              <li>
                <%= link_to cart_items_path, class: 'nav-link text-dark' do %>
                  Cart
                <% end %>
              </li>

              <li>
                <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' do %>
                  Log out
                <% end %>
              </li>

            <% elsif admin_signed_in? %>
            <!--adminログイン時-->
              <li>
                <%= link_to admin_items_path, class: 'nav-link text-dark' do %>
                  商品一覧
                <% end %>
              </li>

              <li>
                <%= link_to admin_customers_path, class: 'nav-link text-dark' do %>
                  会員一覧
                <% end %>
              </li>

              <li>
                <%= link_to admin_orders_path, class: 'nav-link text-dark' do %>
                 注文履歴一覧
                <% end %>
              </li>

              <li>
                <%= link_to admin_genres_path, class: 'nav-link text-dark' do %>
                  ジャンル一覧
                <% end %>
              </li>

              <li>
                <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' do %>
                  ログアウト
                <% end %>
              </li>

            <% else %>
            <!--未ログイン時-->
              <li>
                <%= link_to about_path, class: 'nav-link text-dark' do %>
                  About
                <% end %>
              </li>

              <li>
                <%= link_to items_path, class: 'nav-link text-dark' do %>
                  Items
                <% end %>
              </li>

              <li>
                <%= link_to new_customer_registration_path, class: 'nav-link text-dark' do %>
                  Sign up
                <% end %>
              </li>

              <li>
                <%= link_to new_customer_session_path, class: 'nav-link text-dark' do %>
                  Log in
                <% end %>
              </li>

            <% end %>
          </ul>
        </div>

      </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/c91480665d.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>